### ISSUE TITLE
In what way is this app privacy-friendly ?

### ISSUE THREAD

**Issue by breversa** [SecUSo/privacy-friendly-qr-scanner#1]
Hi there,

I'm wondering what makes this app privacy-friendly, over (for instance) Barcode Scanner (https://github.com/zxing/zxing) ?

**Comment by p-rack** [comment]
Hi there,

this app, as well as other apps from the group of privacy friendly apps, requires only the minimum of permissions (camera for decoding/ vibration for feedback). While the Barcode Scanner brings more functionality, it also requires more permissions. If the user needs these additional functions, he should use the Barcode Scanner. Otherwise for simple decoding of the QR Code, this app is enough and requires less permissions.

**Comment by breversa** [comment]
Thank you for your reply !
So if I understand correctly, it's basically a QR scanner without ad/bloat/spy/trackware ? 

Sad world we live in, that there's a need for that kind of app, while it's just how it SHOULD be ! :-/

**Comment by p-rack** [comment]
You are welcome!
Yes, you understood this correctly. I would not say the Barcode Scanner uses things like ad/bloat/spy or trackware, but because of the permissions apps like this require, you cannot be 100% sure about it. 

Therefore we decided to offer applications which use just the minimum amount of permissions.

**Comment by breversa** [comment]
Well, to be totally honest, vibration control is technically not the *minimum* needed… I'm pretty sure you could do without it ! ;-)
(I understand that vibration permission is not a privacy-related one, but still… I like nitpicking. ;-) )
