### ISSUE TITLE
[Request] Read/write VCards and more

### ISSUE THREAD

**Issue by malnvenshorn** [SecUSo/privacy-friendly-qr-scanner#37]
At the moment this app does only one thing, reading QR codes. But unless you scanned a link you cannot do much with the result. E.g. after you scanned a VCard you still have to add the contact manually and if you scanned login details to a WIFI network you cannot simply connect to it. The same when you want to create QR codes, you have to add all information manually (e.g. this app doesn't show up in the share menu of contacts).

Are those features planned or is the philosophy of this app to use as less permissions as possible and to renounce such convenience features?

**Comment by petermayer** [comment]
Hi @malnvenshorn, as you already correctly assumed, these features are not implemented in our app due to the original design decision to not depend on the respective permissions. And we stand by that decision, since the very careful and conscious decisions regarding the inclusion of permissions is one of the corner stones defining our privacy friendly apps.

Yet, since this decision was made under the install-time permission model and the permission model has now evolved to runtime permissions, it might be re-evaluated at some point in the future. But just to be clear, there are currently no plans to change this.

I will, however, leave this issue open in case others want to join the conversation regarding the addition of these features which require also new permissions.

**Comment by malnvenshorn** [comment]
At least for adding new contacts no additional permission is required if the insertion is delegated to the contacts app.

Connecting to a WiFi network would require `ACCESS_WIFI_STATE` and `CHANGE_WIFI_STATE` if I'm not mistaken. Doesn't seem that privacy unfriendly to me :wink:

**Comment by Kamuno** [comment]
This was added in v2.0. The wifi password still has to be copied but contacts can be added via the contact application on the device.
