### ISSUE TITLE
Changelog 3 years old

### ISSUE THREAD

**Issue by Avispa** [SecUSo/privacy-friendly-qr-scanner#46]
Newest entry is v1.6.x back from 2016 while, at least referring to _F-Droid_, there is jump in version more than a full generation up to v2.2 for real. Please (heavily) consider to keep the Changelog up-to-date.

**Comment by jmichael2497** [comment]
the readme and fastlane descriptions need updates as well, since apparently the latest updates added the ability to create images as well.

i've been using the zxing barcode scanner app (which can read various codes and create only qr codes), but they are not going to update their app to target current apis, so...

in looking for alternative foss replacements, it would be helpful to have the description say based on current zxing library, able to read (list types of codes), able to create (list types of codes), examples of usage, especially useful for not having to type in a long website, swapping contact cards, sharing wifi name and password.

hope that helps.
