### ISSUE TITLE
Is this project still actively maintained? Is it developed by TU-Darmstadt or KIT?

### ISSUE THREAD

**Issue by void-m4110c** [SecUSo/privacy-friendly-qr-scanner#77]
Sorry for bothering, but I have to ask. 

Is there still any active development on this project? And by this I don't mean translations into other languages.

There seem to be quite some unaddressed bugs in the _Issues_ section... 

Also the fact that on the [F-Droid project page](https://f-droid.org/de/packages/com.secuso.privacyFriendlyCodeScanner/) it states that:

> It belongs to the group of Privacy Friendly Apps from the research group SECUSO (Security, Usability and Society) by the **Technische Universität Darmstadt**, Germany.

![image](https://user-images.githubusercontent.com/43680093/89103335-58f1de00-d411-11ea-833b-81064c00d49b.png)

But judging from all other sources it seems that the KIT in Karlsruhe is developing the app. All this seems rather suspicious for a "privacy friendly" app and I don't feel comfortable scanning any sensitive data with this. 

Any clarification is highly appreciated.
Thanks

**Comment by sleep-yearning** [comment]
Hello @void-m4110c !
Thanks for sharing your concerns, which are very understandable. You don't need to worry though. 
SECUSO was formerly part of TU Darmstadt, where many of the PF Apps started. Now it is part of KIT and not all the descriptions have been updated (there are a lot).

As to the issues, there is work done (and I think this one is even worked on currently) but often other pressing work gets in the way, which is why the PF Apps are updated rather slowly. 

If you want to contribute, you can of course help with a Pull Request. ;)

Have a nice week!

**Comment by void-m4110c** [comment]
Thanks for taking the time to answer @sleep-yearning ,

that clears things up. :) 
If I find some time, I might actually look intro contributing. 

Keep up the good work and thanks again for your work.

All the best!
